"""empty message

Revision ID: 0f76e95e8216
Revises: d7ff4a50edb3
Create Date: 2025-04-01 17:32:46.141616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f76e95e8216'
down_revision = 'd7ff4a50edb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['Item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    with op.batch_alter_table('AssetRequest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AssetRequest', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    op.drop_table('stock_inventory')
    # ### end Alembic commands ###
