"""empty message

Revision ID: 95825f5f9c48
Revises: bda3af5e0ebd
Create Date: 2025-04-03 23:05:28.034030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95825f5f9c48'
down_revision = 'bda3af5e0ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('job_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('avatar_hash', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Employee', schema=None) as batch_op:
        batch_op.drop_column('avatar_hash')
        batch_op.drop_column('last_seen')
        batch_op.drop_column('job_description')
        batch_op.drop_column('location')
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###
