"""empty message

Revision ID: bda3af5e0ebd
Revises: 0f76e95e8216
Create Date: 2025-04-02 08:48:57.305821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda3af5e0ebd'
down_revision = '0f76e95e8216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AssetRequest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forwarded', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AssetRequest', schema=None) as batch_op:
        batch_op.drop_column('forwarded')

    # ### end Alembic commands ###
