"""Update

Revision ID: d7ff4a50edb3
Revises: e621498491fb
Create Date: 2025-04-01 16:12:03.889686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ff4a50edb3'
down_revision = 'e621498491fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AssetAssignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('assigned_date', sa.DateTime(), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['Employee.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['Item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('AssetRequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('decision_date', sa.DateTime(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['Employee.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['Item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Asset Requests')
    op.drop_table('Asset Assignment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Asset Assignment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('asset_id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('assigned_date', sa.DATETIME(), nullable=True),
    sa.Column('return_date', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['Asset.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['Employee.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['Item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Asset Requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('asset_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=False),
    sa.Column('request_date', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('approved_by', sa.INTEGER(), nullable=True),
    sa.Column('decision_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['Employee.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['Employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('AssetRequest')
    op.drop_table('AssetAssignment')
    # ### end Alembic commands ###
